mutation CreateGroup($input: CreateGroupInput!) {
  createGroup(input: $input) {
    id
    sourceId
    sourceType
    name
    prompt
    targetSize
    status
    metadata
    createdAt
    updatedAt
    source
  }
}

mutation UpdateGroup($id: ID!, $input: UpdateGroupInput!) {
  updateGroup(id: $id, input: $input)
}

mutation DeleteGroup($id: ID!) {
  deleteGroup(id: $id)
} 